appname="CustomDialog"
appver="1.0.2"
appcode="190724102"
appsdk="21"
path_pattern=""
packagename="com.smalldi.customdialog"
theme="Theme_Material_Light_DarkActionBar"
app_key=""
app_channel=""
developer="SmallDi"
description="纯LuaJava代码编写的高度自定义对话框"
debugmode=true
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
